[package]
name = "kitty"
version = "0.8.0"
authors = ["Adrian Borup <adrian@borup.com>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
colored = "2"
eyre = "0.6"
platform-dirs = "0.3"
rust-ini = "0.18"
secrecy = "0.8"
